name: Generate PR Dashboard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate PR list
        run: |
          ORG_NAME=my-org
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          mkdir -p public
          echo "<h2>Open Pull Requests in $ORG_NAME</h2>" > public/index.html
          echo "<ul>" >> public/index.html
          curl -s -H "Authorization: token $TOKEN" "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100" |
            jq -r '.[].full_name' | while read repo; do
              prs=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$repo/pulls?state=open")
              echo "$prs" | jq -r --arg r "$repo" '.[] | "<li><a href=\"" + .html_url + "\">[" + $r + "] " + .title + "</a></li>"' >> public/index.html
            done
          echo "</ul>" >> public/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs}}
